language: android

android:
        components: 
        - tools
        - platform-tools
        - android-26
        - build-tools-26.0.2

before_install: chmod +x gradlew

jobs:
        include:
                - stage: "Delivery"
                  name: "Build"
                  script: ./gradlew kiosk-delivery-main:assembleDebug
                - script: ./gradlew kiosk-delivery-main:lintDebug
                  name: "Lint"
                - script: ./gradlew kiosk-delivery-main:jacocoTestReport
                  name: "Test"
                - stage: "Feeds"
                  name: "Build"
                  script: ./gradlew kiosk-feeds:assemble
                - script: ./gradlew kiosk-feeds:instrument kiosk-feeds:test kiosk-feeds:report kiosk-feeds:coverageCheck
                  name: "Test"

