language: android

android:
        components: 
        - tools
        - platform-tools
        - android-26
        - build-tools-26.0.2

before_install: chmod +x gradlew

script: ./gradlew kiosk-delivery-main:assembleDebug
